apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
 - name: mysql-pass
   literals:
      - password=rohit
 - name: mysqluser-pass
   literals:
      - myuserpassword=rohit
resources:
   - db.yml
   - owncloud.yml